name: SkyRanks
version: 1.3
main: dev.micah.SkyRanks
commands:
  skyranks:
    description: The main SkyRanks command
    aliases: [sr, skyr, sranks]
  vanish:
    description: Vanish command built into SkyRanks
    aliases: [v, dissapear, hide]
  nick:
    description: Nick command built into SkyRanks
    aliases: [nickname]
  skyranksbeta:
    description: BETA Command only for special people